enablePlugins(SbtWeb)

val js = project

scalaVersion in ThisBuild := "2.11.7"

val scalaJsFiles = taskKey[Seq[File]]("JavaScript files generated by Scala.js")

scalaJsFiles := {
  val jsFile = (fastOptJS in js in Compile).value.data
  val destinationFile = (sourceManaged in Assets).value / jsFile.getName
  IO.copyFile(jsFile, destinationFile)
  Seq(destinationFile)
}

resourceGenerators in Assets <+= scalaJsFiles
